version: '3.7'

services:

  react:
    container_name: react
    build: ./frontend/quizreact
    volumes:
      - './frontend/quizreact:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    depends_on:
      - api

  api:
    build: ./api
    command: bash -c "python manage.py migrate && python manage.py init_data && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
