# Generated by Django 3.0.7 on 2020-06-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="checked",
            field=models.BooleanField(default=False),
        ),
    ]
