# Generated by Django 3.0.7 on 2020-06-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_answer_checked"),
    ]

    operations = [
        migrations.RemoveField(model_name="answer", name="selected_in_question",),
    ]
