# Generated by Django 3.0.7 on 2020-08-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200702_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiziteration',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='iteration',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='iteration', to='quiz.QuizIteration'),
        ),
    ]
